### ISSUE TITLE
Create overviewCArd (US 2)

### ISSUE THREAD

**Issue by muhammed-basaran** [muhammed-basaran/userStories#2]
## Value Proposition

**As a** user

**I need** more informations about the products (color, stories)

**to be able to** to get more details about the product 

## Description
Scribble / design or text

![Bildschirmfoto 2022-12-09 um 15 47 07](https://user-images.githubusercontent.com/115261964/206727917-5cfb88f6-b80c-491a-97ac-56179e437caa.png)

## Acceptance Criteria

- [ ] create bigger card with more details about the product
- [ ] bigger img, more img
- [ ] only 1 card is shown on the screen 
- [ ] one new card for each created card
- [ ] on click you can toggle between both views

## Tasks

(for developers team)

- [ ] work on branch
- [ ] e.g. Components, Storybook, testing
- [ ] create Header with title
- [ ] create 5-6 hardcoded cards
- [ ] give some layout for body and cards 
- [ ] onClick event/routing NextJs

**Comment by ufelgen** [comment]
"on click you can toggle between both views" wo klickt man? kannst du das in deinem Design noch hinzufügen? :)

**Comment by muhammed-basaran** [comment]
> "on click you can toggle between both views" wo klickt man? kannst du das in deinem Design noch hinzufügen? :)

merci, wusste nicht wie ich es beschreiben soll, auf jeden Fall auf die card selbst

**Comment by julialoeschel** [comment]
:octocat:  lgtm

passend zur ersten schlage ich auch hier wieder vor, die Daten vorher zu gererieren und den ganzen Code nicht hart zu coden (Sprat Zeit).

ansonsten sehr gut 👍
